services:
  web:
    build: .
    command: sh -c "npm run build && node dist/api/index.js"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
      - postgres
  worker-ch:
    build: .
    command: sh -c "npm run build && node dist/workers/chAppointments.js"
    env_file: .env
    depends_on:
      - redis
      - postgres
  worker-company:
    build: .
    command: sh -c "npm run build && node dist/workers/companyDiscovery.js"
    env_file: .env
    depends_on:
      - redis
      - postgres
  worker-person:
    build: .
    command: sh -c "npm run build && node dist/workers/personLinkedin.js"
    env_file: .env
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin:
