version: "3.9"
services:
  web:
    build: .
    command: sh -c "npm run build && node dist/api/index.js"
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - redis
  worker-ch:
    build: .
    command: sh -c "npm run build && node dist/workers/chAppointments.js"
    env_file: .env
    depends_on:
      - redis
  worker-company:
    build: .
    command: sh -c "npm run build && node dist/workers/companyDiscovery.js"
    env_file: .env
    depends_on:
      - redis
  worker-person:
    build: .
    command: sh -c "npm run build && node dist/workers/personLinkedin.js"
    env_file: .env
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
