import { Router } from "express";

export const router = Router();

const page = [
  "<!doctype html>",
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>Admin Portal · MarketOffer</title>',
  '  <link rel="apple-touch-icon" sizes="180x180" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/apple-touch-icon.png" />',
  '  <link rel="icon" type="image/png" sizes="32x32" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon-32x32.png" />',
  '  <link rel="icon" type="image/png" sizes="16x16" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon-16x16.png" />',
  '  <link rel="shortcut icon" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon.ico" />',
  '  <style>',
  '    :root { --bg:#0f172a; --card:#111c32; --panel:#0b1220; --muted:#94a3b8; --text:#f8fafc; --accent:#60a5fa; --accent-dark:#2563eb; --border:#1f2937; }',
  '    * { box-sizing:border-box; }',
  '    body { margin:0; min-height:100vh; background:var(--bg); color:var(--text); font-family:"Inter",ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial; display:flex; flex-direction:column; }',
  '    header { padding:28px 22px 12px; display:flex; justify-content:center; }',
  '    header img { height:58px; width:auto; }',
  '    main { flex:1; display:flex; justify-content:center; align-items:center; padding:24px; }',
  '    .panel { width:100%; max-width:540px; background:rgba(17,24,39,0.8); border:1px solid rgba(148,163,184,0.25); border-radius:22px; padding:36px 32px; box-shadow:0 30px 90px rgba(15,23,42,0.55); backdrop-filter: blur(12px); }',
  '    .panel h1 { margin:0 0 10px; font-size:clamp(1.9rem,4vw,2.3rem); text-align:center; }',
  '    .panel p { margin:0 0 28px; color:var(--muted); text-align:center; font-size:1rem; line-height:1.6; }',
  '    .actions { display:flex; flex-direction:column; gap:16px; }',
  '    .cta { display:flex; justify-content:space-between; align-items:center; background:var(--panel); border:1px solid rgba(148,163,184,0.25); border-radius:16px; padding:18px 20px; color:var(--text); text-decoration:none; transition: border-color .15s ease, transform .15s ease, background .15s ease; box-shadow:0 14px 28px rgba(15,23,42,0.45); }',
  '    .cta:hover { border-color:var(--accent); transform:translateY(-2px); background:rgba(37,99,235,0.15); }',
  '    .cta span { font-size:1.05rem; font-weight:600; }',
  '    .cta svg { width:18px; height:18px; color:var(--accent); }',
  '    footer { padding:26px; text-align:center; color:rgba(148,163,184,0.7); font-size:0.85rem; }',
  '    @media (max-width:540px) {',
  '      .panel { padding:32px 24px; }',
  '      header img { height:52px; }',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  <header>',
  '    <a href="/">',
  '      <img src="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/MarketOffer+Logo+-+3000px+Width+Transparent.png" alt="MarketOffer" />',
  '    </a>',
  '  </header>',
  '  <main>',
  '    <section class="panel">',
  '      <h1>Admin Portal</h1>',
  '      <p>Select an option to manage discovery requests and track workflow progress.</p>',
  '      <div class="actions">',
  '        <a class="cta" href="/admin/request?flow=director">',
  '          <span>Director Request</span>',
  '          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">',
  '            <path d="M12 5v14"/><path d="M5 12h14"/>',
  '          </svg>',
  '        </a>',
  '        <a class="cta" href="/admin/request?flow=owner">',
  '          <span>Owner Request</span>',
  '          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">',
  '            <path d="M12 5v14"/><path d="M5 12h14"/>',
  '          </svg>',
  '        </a>',
  '        <a class="cta" href="/admin/requests">',
  '          <span>View All Requests</span>',
  '          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">',
  '            <path d="M5 12h14"/><path d="M12 5l7 7-7 7"/>',
  '          </svg>',
  '        </a>',
  '      </div>',
  '    </section>',
  '  </main>',
  '  <footer>© ' + new Date().getFullYear() + ' MarketOffer. All rights reserved.</footer>',
  '</body>',
  '</html>'
].join('\n');

router.get('/', (_req, res) => {
  res.type('html').send(page);
});
