import { Router } from 'express';

export const router = Router();

const page = [
  '<!doctype html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>Progress Summary</title>',
  '  <style>',
  '    :root { --bg:#0f172a; --panel:#0b1220; --muted:#94a3b8; --text:#f3f4f6; --border:#243041; --accent:#60a5fa; }',
  '    html, body { min-height:100%; margin:0; padding:0; background:var(--bg); color:var(--text); font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Inter, Arial; }',
  '    body { padding-bottom:60px; }',
  '    .nav { display:flex; gap:10px; justify-content:center; padding:24px 12px 12px; }',
  '    .nav .btn { padding:8px 12px; border-radius:8px; border:1px solid var(--border); background:#101a2d; color:var(--text); text-decoration:none; font-size:14px; transition:background .15s ease, border-color .15s ease; }',
  '    .nav .btn:hover { background:#16213a; border-color:#2d3b52; }',
  '    .nav .btn.active { background:#1f2a40; border-color:#334155; }',
  '    .nav .btn.disabled { opacity:0.55; pointer-events:none; cursor:default; }',
  '    .wrap { max-width:1000px; margin:0 auto; padding:12px 20px 40px; }',
  '    .hdr { display:flex; align-items:center; justify-content:space-between; gap:12px; margin-bottom:18px; }',
  '    .hdr .title { font-size:26px; font-weight:700; }',
  '    .hdr .muted { color:var(--muted); font-size:14px; }',
  '    .placeholder { background:var(--panel); border:1px dashed rgba(96,165,250,0.4); border-radius:12px; padding:20px; color:var(--muted); font-size:14px; line-height:1.5; }',
  '    .placeholder strong { color:var(--text); }',
  '  </style>',
  '</head>',
  '<body>',
  '  <nav class="nav" data-current="progress">',
  '    <a class="btn" data-role="nav-btn" data-target="requests" data-base="/admin/requests" href="/admin/requests">View Requests</a>',
  '    <a class="btn" data-role="nav-btn" data-target="request" data-base="/admin/request" href="/admin/request">New Request</a>',
  '    <a class="btn" data-role="nav-btn" data-target="progress" data-base="/admin/progress" data-requires-root="1" href="/admin/progress">Progress Summary</a>',
  '    <a class="btn" data-role="nav-btn" data-target="workflows" data-base="/admin/workflows" data-requires-root="1" href="/admin/workflows">Workflow Detail</a>',
  '  </nav>',
  '  <div class="wrap">',
  '    <div class="hdr">',
  '      <div class="title">Progress Summary</div>',
  '      <div class="muted">High-level snapshot of workflow health.</div>',
  '    </div>',
  '    <div class="placeholder">',
  '      <p>This page is ready for a deeper summary view. Share the desired layout and we will surface the relevant metrics here.</p>',
  '      <p>Current selection: <strong id="currentRoot">None</strong></p>',
  '    </div>',
  '  </div>',
  '  <script>',
  "    const navButtons = Array.from(document.querySelectorAll('[data-role=\"nav-btn\"]'));",
  '    const navCurrent = document.querySelector(".nav")?.dataset.current || "";',
  '    function applyNavRoot(root) {',
  '      navButtons.forEach((btn) => {',
  '        const target = btn.dataset.target || "";',
  '        if (target === navCurrent) { btn.classList.add("active"); } else { btn.classList.remove("active"); }',
  '        const base = btn.dataset.base || btn.getAttribute("href") || "#";',
  '        if (btn.dataset.requiresRoot === "1") {',
  '          if (root) {',
  '            btn.setAttribute("href", `${base}?root=${encodeURIComponent(root)}`);',
  '            btn.classList.remove("disabled");',
  '            btn.setAttribute("aria-disabled", "false");',
  '          } else {',
  '            btn.setAttribute("href", "#");',
  '            btn.classList.add("disabled");',
  '            btn.setAttribute("aria-disabled", "true");',
  '          }',
  '        } else {',
  '          btn.setAttribute("href", base);',
  '        }',
  '      });',
  '      const rootLabel = document.getElementById("currentRoot");',
  '      if (rootLabel) rootLabel.textContent = root || "None";',
  '      window.__currentNavRoot = root;',
  '    }',
  '    window.__setNavRoot = applyNavRoot;',
  '    const initRoot = new URLSearchParams(window.location.search).get("root") || "";',
  '    applyNavRoot(initRoot);',
  '  </script>',
  '</body>',
  '</html>'
].join('\n');

router.get('/', (_req, res) => {
  res.type('html').send(page);
});
