import { Router } from 'express';

export const router = Router();

const page = [
  '<!doctype html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>New Discovery Request</title>',
  '  <style>',
  '    :root { --bg:#0f172a; --panel:#0b1220; --muted:#9ca3af; --text:#f3f4f6; --border:#243041; --accent:#60a5fa; }',
  '    html, body { height:100%; margin:0; padding:0; background:var(--bg); color:var(--text); font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Inter, Arial; }',
  '    .wrap { max-width:640px; margin:40px auto; padding:20px; background:var(--panel); border:1px solid var(--border); border-radius:12px; }',
  '    h1 { margin:0 0 16px 0; font-size:20px; }',
  '    .row { display:flex; gap:14px; }',
  '    label { display:block; font-size:12px; color:var(--muted); margin:10px 0 6px; }',
  '    input { width:100%; box-sizing:border-box; background:#0a0f1d; color:var(--text); border:1px solid var(--border); padding:10px 12px; border-radius:8px; }',
  '    button { margin-top:18px; padding:10px 14px; border-radius:8px; border:1px solid var(--border); background:#101a2d; color:var(--text); cursor:pointer; }',
  '    button:disabled { opacity:0.6; cursor:not-allowed; }',
  '    .hint { color:var(--muted); font-size:12px; margin-top:8px; }',
  '    .err { color:#fecaca; margin-top:10px; }',
  '    a { color:var(--accent); text-decoration:none; }',
  '  </style>',
  '</head>',
  '<body>',
  '  <div class="wrap">',
  '    <div style="display:flex;align-items:center;justify-content:space-between;gap:10px;">',
  '      <h1 style="margin:0">Start Discovery</h1>',
  '      <a href="/admin/settings" title="Settings" style="margin:0;padding:8px 10px;display:inline-flex;align-items:center;gap:8px;border:1px solid #243041;border-radius:8px;background:#101a2d;color:#f3f4f6;">',
  '        <span>Settings</span>',
  '        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">',
  '          <circle cx="12" cy="12" r="3"></circle>',
  '          <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09a1.65 1.65 0 0 0-1-1.51 1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09a1.65 1.65 0 0 0 1.51-1 1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33h0A1.65 1.65 0 0 0 10.91 3H11a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51h0a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82v0A1.65 1.65 0 0 0 21 10.91V11a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"></path>',
  '        </svg>',
  '      </a>',
  '    </div>',
  '    <form id="frm">',
  '      <div class="row">',
  '        <div style="flex:1">',
  '          <label for="firstName">First name</label>',
  '          <input id="firstName" name="firstName" placeholder="Jane" />',
  '        </div>',
  '        <div style="flex:1">',
  '          <label for="lastName">Last name</label>',
  '          <input id="lastName" name="lastName" placeholder="Doe" />',
  '        </div>',
  '      </div>',
  '      <div class="row">',
  '        <div style="flex:1">',
  '          <label for="recordId">Record ID (optional)</label>',
  '          <input id="recordId" name="recordId" placeholder="recXXXXXXXXXXXXXX" />',
  '        </div>',
  '        <div style="flex:1">',
  '          <label for="companyNumber">Company Number</label>',
  '          <input id="companyNumber" name="companyNumber" placeholder="01234567" required />',
  '        </div>',
  '      </div>',
  '      <button id="go" type="submit">Start</button>',
  '      <div class="hint">You will be redirected to the tracking page after the job is created.</div>',
  '      <div id="err" class="err"></div>',
  '    </form>',
  '  </div>',
  '  <script>',
  '    const el = (id) => document.getElementById(id);',
  '    el("frm").addEventListener("submit", async (e) => {',
  '      e.preventDefault();',
  '      el("err").textContent = "";',
  '      const btn = el("go"); btn.disabled = true; btn.textContent = "Starting…";',
  '      const firstName = el("firstName").value.trim();',
  '      const lastName = el("lastName").value.trim();',
  '      const contactId = el("recordId").value.trim();',
  '      const companyNumber = el("companyNumber").value.trim();',
  '      if (!companyNumber) { el("err").textContent = "Company number is required"; btn.disabled = false; btn.textContent = "Start"; return; }',
  '      try {',
  '        const res = await fetch("/api/jobs/ch-appointments", {',
  '          method: "POST",',
  '          headers: { "Content-Type": "application/json" },',
  '          body: JSON.stringify({ companyNumber, firstName, lastName, contactId })',
  '        });',
  '        if (!res.ok) throw new Error("Request failed: " + res.status);',
  '        const data = await res.json();',
  '        const jobId = data.jobId;',
  '        if (!jobId) throw new Error("No jobId returned");',
  '        window.location.href = "/admin/workflows?root=" + encodeURIComponent(jobId);',
  '      } catch (err) {',
  '        el("err").textContent = String(err);',
  '      } finally {',
  '        btn.disabled = false; btn.textContent = "Start";',
  '      }',
  '    });',
  '  </script>',
  '</body>',
  '</html>'
].join('\n');

router.get('/', (_req, res) => {
  res.type('html').send(page);
});
