import { Router } from 'express';

export const router = Router();

const page = [
  '<!doctype html>',
  '<html lang="en">',
  '<head>',
  '  <meta charset="utf-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
  '  <title>Discovery Workflows</title>',
  '  <link rel="apple-touch-icon" sizes="180x180" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/apple-touch-icon.png" />',
  '  <link rel="icon" type="image/png" sizes="32x32" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon-32x32.png" />',
  '  <link rel="icon" type="image/png" sizes="16x16" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon-16x16.png" />',
  '  <link rel="shortcut icon" href="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/Favicons/favicon.ico" />',
  '  <style>',
  '    :root { --bg:#0f172a; --panel:#111c32; --muted:#9ca3af; --text:#f3f4f6; --accent:#60a5fa; --border:#243041; }',
  '    * { box-sizing:border-box; }',
  '    html, body { margin:0; min-height:100vh; background:var(--bg); color:var(--text); font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Inter, Arial; }',
  '    body { display:flex; flex-direction:column; }',
  '    .nav { display:flex; gap:16px; justify-content:center; padding:18px 12px; background:rgba(9,15,29,0.65); border-bottom:1px solid var(--border); flex-wrap:wrap; align-items:center; position:sticky; top:0; z-index:10; backdrop-filter:blur(10px); }',
  '    .nav-brand { display:flex; align-items:center; gap:10px; margin-right:12px; }',
  '    .nav-brand img { height:38px; width:auto; }',
  '    .nav .btn { padding:8px 12px; border-radius:8px; border:1px solid var(--border); background:#101a2d; color:var(--text); text-decoration:none; font-size:14px; transition:background .15s ease, border-color .15s ease; }',
  '    .nav .btn:hover { background:#16213a; border-color:#2d3b52; }',
  '    .nav .btn.active { background:#1f2a40; border-color:#334155; }',
  '    .nav .btn.disabled { opacity:0.55; pointer-events:none; cursor:default; }',
  '    main { flex:1; display:flex; justify-content:center; padding:24px 16px 40px; }',
  '    .wrap { width:100%; max-width:1100px; display:flex; flex-direction:column; gap:16px; }',
  '    .card { background:var(--panel); border:1px solid var(--border); border-radius:16px; padding:20px; box-shadow:0 25px 55px rgba(15,23,42,0.45); }',
  '    .heading { display:flex; flex-wrap:wrap; justify-content:space-between; align-items:center; gap:16px; }',
  '    .heading h1 { margin:0; font-size:1.6rem; }',
  '    .heading small { color:var(--muted); }',
  '    .summary { display:flex; flex-wrap:wrap; gap:12px; margin-top:14px; }',
  '    .summary .tile { background:#0b1220; border:1px solid var(--border); border-radius:12px; padding:10px 14px; font-size:0.92rem; }',
  '    .controls { display:flex; gap:12px; flex-wrap:wrap; align-items:center; }',
  '    .controls button, .controls select { padding:8px 12px; border-radius:10px; border:1px solid var(--border); background:#101a2d; color:var(--text); font-size:0.95rem; cursor:pointer; }',
  '    .controls button:hover { background:#16213a; border-color:#2d3b52; }',
  '    .controls select { cursor:pointer; }',
  '    .timeline { display:flex; flex-direction:column; gap:10px; max-height:60vh; overflow:auto; padding-right:6px; }',
  '    .event { display:grid; grid-template-columns: 200px 120px 1fr; gap:14px; padding:12px 14px; border:1px solid rgba(36,48,65,0.75); border-radius:12px; background:rgba(10,17,32,0.75); }',
  '    .event .ts { color:var(--muted); font-size:0.88rem; }',
  '    .event .queue { font-size:0.9rem; color:#cbd5e1; }',
  '    .event .msg .m { font-weight:600; margin-bottom:6px; }',
  '    .event pre { margin:0; white-space:pre-wrap; background:#050b18; border:1px solid #1e293b; padding:8px; border-radius:8px; color:#d1d5db; font-size:0.85rem; }',
  '    .empty { padding:20px; text-align:center; color:var(--muted); }',
  '  </style>',
  '</head>',
  '<body>',
  '  <nav class="nav" data-current="workflows">',
  '    <a class="nav-brand" href="/">',
  '      <img src="https://marketoffer-public-resources.s3.eu-west-2.amazonaws.com/MarketOffer+Icon+-+500px+Width+Inc+Border.png" alt="MarketOffer" />',
  '    </a>',
  '    <a class="btn" data-role="nav-btn" data-target="requests" data-base="/admin/requests" href="/admin/requests">View Requests</a>',
  '    <a class="btn" data-role="nav-btn" data-target="request" data-base="/admin/request" href="/admin/request">New Request</a>',
  '    <a class="btn" data-role="nav-btn" data-target="progress" data-base="/admin/progress" data-requires-root="1" href="/admin/progress">Progress Summary</a>',
  '    <a class="btn" data-role="nav-btn" data-target="workflows" data-base="/admin/workflows" data-requires-root="1" href="/admin/workflows">Workflow Detail</a>',
  '  </nav>',
  '  <main>',
  '    <div class="wrap">',
  '      <section class="card">',
  '        <div class="heading">',
  '          <div>',
  '            <h1 id="title">Workflow</h1>',
  '            <small id="subs"></small>',
  '          </div>',
  '          <div class="controls">',
  '            <label style="display:flex; align-items:center; gap:6px; font-size:0.9rem; color:var(--muted);">',
  '              Log filter',
  '              <select id="logFilter">',
  '                <option value="all">All levels</option>',
  '                <option value="info">Info</option>',
  '                <option value="debug">Debug</option>',
  '                <option value="warn">Warn</option>',
  '                <option value="error">Error</option>',
  '              </select>',
  '            </label>',
  '            <button id="refresh">Refresh</button>',
  '          </div>',
  '        </div>',
  '        <div class="summary" id="summary"></div>',
  '      </section>',
  '      <section class="card">',
  '        <div class="timeline" id="timeline"></div>',
  '        <div class="empty" id="emptyState" style="display:none;">No workflow selected.</div>',
  '      </section>',
  '    </div>',
  '  </main>',
  '  <script>',
  "    const navButtons = Array.from(document.querySelectorAll('[data-role=\"nav-btn\"]'));",
  '    const navCurrent = document.querySelector(".nav")?.dataset.current || "";',
  '    function applyNavRoot(root) {',
  '      navButtons.forEach((btn) => {',
  '        const target = btn.dataset.target || "";',
  '        if (target === navCurrent) { btn.classList.add("active"); } else { btn.classList.remove("active"); }',
  '        const base = btn.dataset.base || btn.getAttribute("href") || "#";',
  '        if (btn.dataset.requiresRoot === "1") {',
  '          if (root) {',
  '            btn.setAttribute("href", `${base}?root=${encodeURIComponent(root)}`);',
  '            btn.classList.remove("disabled");',
  '            btn.setAttribute("aria-disabled", "false");',
  '          } else {',
  '            btn.setAttribute("href", "#");',
  '            btn.classList.add("disabled");',
  '            btn.setAttribute("aria-disabled", "true");',
  '          }',
  '        } else {',
  '          btn.setAttribute("href", base);',
  '        }',
  '      });',
  '      window.__currentNavRoot = root;',
  '    }',
  '    window.__setNavRoot = applyNavRoot;',
  '    const params = new URLSearchParams(window.location.search);',
  '    const rootId = params.get("root") || "";',
  '    applyNavRoot(rootId);',
  '    const fmtTs = (s) => new Date(s).toLocaleString();',
  '    const el = (html) => { const d = document.createElement("div"); d.innerHTML = html; return d.firstElementChild; };',
  '    const safe = (o) => { try { return JSON.stringify(o, null, 2); } catch { return String(o); } };',
  '    const summaryEl = document.getElementById("summary");',
  '    const timelineEl = document.getElementById("timeline");',
  '    const titleEl = document.getElementById("title");',
  '    const subsEl = document.getElementById("subs");',
  '    const emptyEl = document.getElementById("emptyState");',
  '    const filterEl = document.getElementById("logFilter");',
  '    const refreshBtn = document.getElementById("refresh");',
  '    let rawEvents = [];',
  '    function renderTimeline() {',
  '      timelineEl.innerHTML = "";',
  '      const filter = (filterEl.value || "all").toLowerCase();',
  '      const events = rawEvents.filter(ev => filter === "all" || (ev.level || "").toLowerCase() === filter);',
  '      if (!events.length) { timelineEl.innerHTML = "<div class=\\"empty\\">No events for this filter.</div>"; return; }',
  '      events.forEach(ev => {',
  '        const q = ev.queue || "";',
  '        const dataHtml = ev.data ? `<pre>${safe(ev.data)}</pre>` : "";',
  '        timelineEl.appendChild(el(`\n'+
  '          <div class="event">\n'+
  '            <div class="ts">${fmtTs(ev.ts)}</div>\n'+
  '            <div class="queue">${q || "&nbsp;"}</div>\n'+
  '            <div class="msg"><div class="m">${ev.message}</div>${dataHtml}</div>\n'+
  '          </div>\n'+
  '        `));',
  '      });',
  '    }',
  '    async function loadWorkflow() {',
  '      if (!rootId) {',
  '        titleEl.textContent = "Workflow";',
  '        subsEl.textContent = "";',
  '        summaryEl.innerHTML = "";',
  '        timelineEl.innerHTML = "";',
  '        emptyEl.style.display = "block";',
  '        refreshBtn.disabled = true;',
  '        return;',
  '      }',
  '      refreshBtn.disabled = true;',
  '      titleEl.textContent = `Workflow ${rootId}`;',
  '      subsEl.textContent = "";',
  '      summaryEl.innerHTML = "";',
  '      timelineEl.innerHTML = "Loading…";',
  '      emptyEl.style.display = "none";',
  '      try {',
  '        const [detailRes, tlRes] = await Promise.all([',
  '          fetch(`/api/progress/workflows/${encodeURIComponent(rootId)}`),',
  '          fetch(`/api/progress/workflows/${encodeURIComponent(rootId)}/timeline`)',
  '        ]);',
  '        if (!detailRes.ok || !tlRes.ok) throw new Error("Request failed");',
  '        const detail = await detailRes.json();',
  '        const tl = await tlRes.json();',
  '        const root = detail.root;',
  '        const companies = (root && root.data && root.data.enqueued && root.data.enqueued.companies) ? root.data.enqueued.companies : [];',
  '        const comp = detail.jobs.company.length, site = detail.jobs.sitefetch.length, person = detail.jobs.person.length;',
  '        summaryEl.appendChild(el(`<div class="tile">Companies Enqueued: <b>${companies.length}</b></div>`));',
  '        summaryEl.appendChild(el(`<div class="tile">Company Jobs: <b>${comp}</b></div>`));',
  '        summaryEl.appendChild(el(`<div class="tile">Site Jobs: <b>${site}</b></div>`));',
  '        summaryEl.appendChild(el(`<div class="tile">Person Jobs: <b>${person}</b></div>`));',
  '        const jobQueue = new Map();',
  '        Object.values(detail.jobs).flat().forEach(j => jobQueue.set(j.job_id, j.queue));',
  '        rawEvents = Array.isArray(tl.events) ? tl.events.slice().reverse().map(ev => ({ ...ev, queue: jobQueue.get(ev.job_id) || "" })) : [];',
  '        renderTimeline();',
  '        refreshBtn.disabled = false;',
  '      } catch (err) {',
  '        timelineEl.innerHTML = `<div class=\\"empty\\">Unable to load workflow: ${err}</div>`;',
  '        summaryEl.innerHTML = "";',
  '        refreshBtn.disabled = false;',
  '      }',
  '    }',
  '    refreshBtn.addEventListener("click", loadWorkflow);',
  '    filterEl.addEventListener("change", renderTimeline);',
  '    loadWorkflow();',
  '  </script>',
  '</body>',
  '</html>'
].join('\n');

router.get('/', (_req, res) => {
  res.type('html').send(page);
});
